# -*- coding: utf-8 -*-
"""11july 2023 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MenxzmjBF_K-A0VRa96o84zFjJDScrDs
"""

x = input("Enter a string: ")

odd_characters = ""
for i in range(len(x)):
    if i % 2 != 0:
        odd_characters += x[i]

print("Characters at odd positions:", odd_characters)

x = input("Enter a string: ")
consonants = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"
count = 0

for char in x:
    if char in consonants:
        count += 1

print("Total number of consonants:", count)

for number in range(1, 100):
    if number % 7 == 0:
        print(number)

for number in range(1, 100):
    if number % 7 == 0 and number % 9 == 0:
      print(number)

for number in range(1, 100):
    if number % 2 == 0:
        print(number)

for number in range(1, 100):
    digit_sum = sum(int(digit) for digit in str(number))
    if digit_sum % 3 == 0:
        print(number)

number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))

if number1 % 4 == 0 and number2 % 6 == 0:
    print(f"{number1} is divisible by 4 and {number2} is divisible by 6.")
else:
    print(f"{number1} is not divisible by 4 and/or {number2} is not divisible by 6.")

number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))

if number1 % 4 == 0 and number2 % 6 == 0:
    if number1 % 4 == 0 and number2 % 6 == 0:
        print(f"{number1} is divisible by 4 and {number2} is divisible by 6.")
    else:
        print(f"{number1} is divisible by 4 but {number2} is not divisible by 6.")
elif number1 % 4 == 0:
    print(f"{number1} is divisible by 4 but {number2} is not divisible by 6.")
elif number2 % 6 == 0:
    print(f"{number2} is divisible by 6 but {number1} is not divisible by 4.")
else:
    print(f"Neither {number1} is divisible by 4 nor {number2} is divisible by 6.")

variable = 35

if variable > 20:
    print("The value of the variable is greater than 20.")

if variable == 23:
    print("The value of the variable is 23.")

if 30 < variable < 40:
    print("The value of the variable is greater than 30 and less than 40.")

